default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_dev
  username: psqluser
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: todo_production
  username: psqluser
  password: password
